version: 1.0.{build}
os: Visual Studio 2015
configuration: CI

environment:
  UNITY_USERNAME:
    secure: KA8oyGmubI+sMRhdpBIEHan8puDTBjP8isbbvsp2yrQ=
  UNITY_PASSWORD:
    secure: dlWlocMuC9JzLPAfxiVnkA==	
  UNITY_SERIAL:
    secure: umfXhelbnLs/iVcdxIU3yeTcqcJhLdTJOp+ebLjF/7I=

cache:
- C:\ProgramData\chocolatey\lib
            
install:
- cmd: choco install Unity

before_build:
- cmd: nuget restore .\src\Solution\Buildron.ClassicMods.sln

build:
  project: .\src\Solution\Buildron.ClassicMods.sln
    
after_build:
- cmd: >-     
    @call start "C:\Program Files\Unity\Editor\Unity.exe" -quit -serial %UNITY_SERIAL% -username "UNITY_USERNAME" -password "UNITY_PASSWORD" 
 
    .\tools\buildModAssets-CI.cmd BuildMod %UNITY_USERNAME% %UNITY_PASSWORD% %UNITY_SERIAL%
    
    .\tools\buildModAssets-CI.cmd EasterEggMod %UNITY_USERNAME% %UNITY_PASSWORD% %UNITY_SERIAL%
    
    .\tools\buildModAssets-CI.cmd EnvironmentMod %UNITY_USERNAME% %UNITY_PASSWORD% %UNITY_SERIAL%
    
    .\tools\buildModAssets-CI.cmd UserMod %UNITY_USERNAME% %UNITY_PASSWORD% %UNITY_SERIAL%
 
on_failure:
- cmd: >-      
     appveyor PushArtifact C:\Users\appveyor\AppData\Local\Unity\Editor\Editor.log

#artifacts:
#  - path: .\build
#    name: build.zip
#  - path: 
#    name: Editor.log