version: 1.0.{build}
os: Visual Studio 2015
configuration: CI

install:
- cmd: choco install Unity

build:
  project: .\src\Solution\Buildron.ClassicMods.sln
  verbosity: minimal
    
after_build:
- cmd: >-     
    .\tools\buildModAssets-CI.cmd BuildMod
    .\tools\buildModAssets-CI.cmd EasterEggMod
    .\tools\buildModAssets-CI.cmd EnvironmentMod
    .\tools\buildModAssets-CI.cmd UserMod

artifacts:
  - path: .\build
    name: build.zip