version: 1.0.{build}
os: Visual Studio 2015
configuration: CI

cache:
- C:\ProgramData\chocolatey\lib
            
install:
- cmd: choco install Unity

before_build:
- cmd: nuget restore .\src\Solution\Buildron.ClassicMods.sln

build:
  project: .\src\Solution\Buildron.ClassicMods.sln
    
after_build:
- cmd: >-     
    .\tools\buildModAssets-CI.cmd BuildMod
    
    .\tools\buildModAssets-CI.cmd EasterEggMod
    
    .\tools\buildModAssets-CI.cmd EnvironmentMod
    
    .\tools\buildModAssets-CI.cmd UserMod

artifacts:
  - path: .\build
    name: build.zip
  - path: C:\Users\appveyor\AppData\Local\Unity\Editor\Editor.log
    name: Editor.log