@echo Building %1 mod assets...
echo on
@"C:\Program Files\Unity\Editor\Unity.exe" -projectPath  C:\projects\buildron-classic-mods\src\Buildron.ClassicMods.%1 -force-free -silent-crashes -nographics -quit -batchmode -username "%2" -password "%3" -executeMethod ModBuilder.BuildFromCommandLine C:\projects\buildron-classic-mods\build StandaloneWindows